export interface Props {
  id: number,
  name: string,
  headerColor: string,
  description: string,
  href: string,
  background: string,
  isReact?: boolean,
  isNext?: boolean,
  isTypeScript?: boolean,
  isTailwind?: boolean,
  isStyledComponents?: boolean,
  isSolidity?: boolean,
  isGoogle?: boolean,
  isAzure?: boolean,
  isPython?: boolean,
  isFlask?: boolean,
  isSQL?: boolean,
  isSass?: boolean,
  isStrapi?: boolean,
  isBootstrap?: boolean,
  isEthereum?: boolean,
  isPostgres?: boolean,
  isMaterialui?: boolean
}

export const projectCardItems: Props[] = [
  { id: 1, name: "Cloudchain", headerColor: "#9B60B8",
  description: "Cloudchain is a web application where you can transfer crypto assets all around the globe.",
  href: "https://cloudchain.vercel.app", background: "url(../../../static/img/bubblePurple.svg)", isReact: true, 
  isNext: true, isTypeScript: true, isTailwind: true, isStyledComponents: true, isSolidity: true, isEthereum: true },
  { id: 2, name: "Los Tercios", headerColor: "#efa50e",
  description: "Los Tercios is a fullstack project developed for people getting familiar with weighlifting and are intersted in lifting in Madrid.",
  href: "https://github.com/Yevhenbk/los-tercios", background: "url(../../../static/img/bubblePeach.svg)", isReact: true, 
  isTypeScript: true, isSass: true, isBootstrap: true, isPython: true, isFlask: true, isSQL: true, isPostgres: true },
  { id: 3, name: "Worksut", headerColor: "#FF524A",
  description: "Responsive, fully animated desktop-only landing page developed for Worksut startup.",
  href: "https://worksut.netlify.app", background: "url(../../../static/img/bubblePink.svg)", isReact: true, 
  isTypeScript: true, isStyledComponents: true, isAzure: true },
  { id: 4, name: "Travel Advisor", headerColor: "black",
  description: "Travely is a web app that serves for providing top rated places you’re willing to find depending on your location.",
  href: "https://lamentable-record.surge.sh", background: "url(../../../static/img/bubbleBlack.svg)", isReact: true, 
  isSass: true, isBootstrap: true, isGoogle: true, isMaterialui: true },
  { id: 5, name: "Technical Challenge", headerColor: "#EE679F",
  description: "Technical Challenge that consist of Calculator, Quotes API, and Metamask connect.",
  href: "https://63347316ca969e094b51dbed--peppy-beijinho-1dd33a.netlify.app", background: "url(../../../static/img/bubblePink.svg)", 
  isReact: true, isNext: true, isTypeScript: true, isStyledComponents: true, isEthereum: true },
  { id: 6, name: "Marvel Characters", headerColor: "#A71C21",
  description: "This project is an app that is connected to external APIs and showing the result from it, which is marvel characters.",
  href: "https://monumental-conkies-9acc89.netlify.app", background: "url(../../../static/img/bubbleRed.svg)", isReact: true, 
  isStyledComponents: true, isStrapi: true },  
]