import Head from 'next/head'

type Props = {
  title: string,
  name?: string
}

export function Layout(props: Props) {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name={props.name} content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}